ALTER TABLE subject_areas
ADD COLUMN class_time TIME DEFAULT NULL,
ADD COLUMN class_end_time TIME DEFAULT NULL,
ADD COLUMN class_day VARCHAR(20) DEFAULT NULL,
ADD COLUMN hours_per_week INT DEFAULT 1;
