import React from 'react';

const ProfileInfo = ({ formData, handleInputChange, photoPreview }) => {
  return (
    <section className="section">
      <h2>Basic Information</h2>
      {/* Removed Employee ID input field as it is auto-generated by the database */}
      <div className="input-group">
        <label className="label" htmlFor="name">Full Name*:</label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name}
          onChange={handleInputChange}
          required
          className="input"
        />
      </div>
      <div className="input-group">
        <label className="label" htmlFor="email">Email*:</label>
        <input
          type="email"
          id="email"
          name="email"
          value={formData.email}
          onChange={handleInputChange}
          className="input"
          required
        />
      </div>
      <div className="input-group">
        <label className="label" htmlFor="contact_number">Contact Number*:</label>
        <input
          type="tel"
          id="contact_number"
          name="contact_number"
          value={formData.contact_number}
          onChange={handleInputChange}
          className="input"
          pattern="^\\+?[0-9\\-\\s]{7,15}$"
          title="Enter a valid phone number"
          required
        />
      </div>
      <div className="input-group">
        <label className="label" htmlFor="position">Position*:</label>
        <input
          type="text"
          id="position"
          name="position"
          value={formData.position}
          onChange={handleInputChange}
          required
          className="input"
        />
      </div>
      <div className="input-group">
        <label className="label" htmlFor="department">Department*:</label>
        <input
          type="text"
          id="department"
          name="department"
          value={formData.department}
          onChange={handleInputChange}
          required
          className="input"
        />
      </div>
      <div className="input-group">
        <label className="label" htmlFor="photo">Profile Picture:</label>
        <input
          type="file"
          id="photo"
          name="photo"
          accept="image/*"
          onChange={handleInputChange}
          className="input"
        />
      </div>
      {photoPreview && <img src={photoPreview} alt="Profile Preview" className="preview-image" />}
      <div className="input-group">
        <label className="label" htmlFor="csv_upload">Upload Employee Data (CSV):</label>
        <input
          type="file"
          id="csv_upload"
          name="csv_upload"
          accept=".csv"
          onChange={(e) => {
            if (e.target.files.length > 0) {
              const file = e.target.files[0];
              if (typeof window !== 'undefined' && window.FileReader) {
                const reader = new FileReader();
                reader.onload = (event) => {
                  const text = event.target.result;
                  if (typeof window !== 'undefined' && window.dispatchEvent) {
                    window.dispatchEvent(new CustomEvent('csvUpload', { detail: text }));
                  }
                };
                reader.readAsText(file);
              }
            }
          }}
          className="input"
        />
      </div>
    </section>
  );
};

export default ProfileInfo;
